
spring:
  # h2 설정
#  sql:
#    init:
#      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:concert-reservation-service
    username: sa

  # jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
#    defer-datasource-initialization: true
  application.name: hhplus-lecture

#logging:
#  level:
#    org.hibernate.type: info
server:
  port: 8082

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true